"""initial data 1

Revision ID: 3f01803ea889
Revises: 54fba85936e2
Create Date: 2024-12-03 14:40:51.594919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f01803ea889"
down_revision: Union[str, None] = "54fba85936e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contracts", sa.Column("total_amount", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "total_amount")
    # ### end Alembic commands ###
