"""'initials'

Revision ID: 5467a9c610d2
Revises: 3f01803ea889
Create Date: 2024-12-17 19:57:06.900960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5467a9c610d2'
down_revision: Union[str, None] = '3f01803ea889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    op.drop_table('admin')
    op.add_column('contracts', sa.Column('last_renewed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'last_renewed')
    op.create_table('admin',
    sa.Column('alumni_group_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['alumni_group_id'], ['alumni_groups.id'], name='admin_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admin_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('claims',
    sa.Column('alumni_member_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('benefit_id', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=False),
    sa.Column('claim_date', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['alumni_member_id'], ['group_members.id'], name='claims_ibfk_1'),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], name='claims_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
