"""add ondelet to beneficiary1

Revision ID: 54fba85936e2
Revises: abdc3df9ff34
Create Date: 2024-12-03 12:49:41.438542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54fba85936e2"
down_revision: Union[str, None] = "abdc3df9ff34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alumni_groups",
        sa.Column("current_invoice_id", sa.String(length=60), nullable=True),
    )
    op.create_foreign_key(
        None,
        "alumni_groups",
        "invoices",
        ["current_invoice_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "alumni_groups", type_="foreignkey")
    op.drop_column("alumni_groups", "current_invoice_id")
    # ### end Alembic commands ###
