"""'intials'

Revision ID: 6779e16aca2f
Revises: f51836fb3201
Create Date: 2024-12-22 05:27:14.841612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6779e16aca2f'
down_revision: Union[str, None] = 'f51836fb3201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'version')
    # ### end Alembic commands ###
