"""add ondelet to beneficiary1

Revision ID: abdc3df9ff34
Revises: 
Create Date: 2024-12-02 16:23:15.495477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abdc3df9ff34"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("beneficiaries_ibfk_2", "beneficiaries", type_="foreignkey")
    op.create_foreign_key(
        None,
        "beneficiaries",
        "group_members",
        ["group_member_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "beneficiaries", type_="foreignkey")
    op.create_foreign_key(
        "beneficiaries_ibfk_2",
        "beneficiaries",
        "group_members",
        ["group_member_id"],
        ["id"],
    )
    # ### end Alembic commands ###
