"""'intials'

Revision ID: f51836fb3201
Revises: 5467a9c610d2
Create Date: 2024-12-22 03:14:34.913033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51836fb3201'
down_revision: Union[str, None] = '5467a9c610d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('renewal_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'renewal_count')
    # ### end Alembic commands ###
